apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: django-api
  name: deployment-django-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-api
  template:
    metadata:
      labels:
        app: django-api
    spec:
      containers:
      - name: django-api
        image: 
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
