# Generated by Django 3.0.2 on 2020-01-27 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id_carro', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('placa', models.CharField(max_length=10)),
                ('quilometragem', models.IntegerField()),
            ],
            options={
                'db_table': 'carro',
            },
        ),
        migrations.CreateModel(
            name='Cdc',
            fields=[
                ('id_cdc', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cdc',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id_registro', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('data_inicial', models.DateField(auto_now_add=True)),
                ('data_final', models.DateField()),
                ('condutor', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('quilometragem_inicial', models.IntegerField()),
                ('quilometragem_final', models.IntegerField()),
                ('id_carro', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Carro')),
                ('id_cdc', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Cdc')),
            ],
            options={
                'db_table': 'registro',
            },
        ),
    ]
